### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by RegulusSource** [SolidBlock-cn/mishanguc#4]
[minecraft-exported-crash-info-2023-05-17T22-26-04.zip](https://github.com/SolidBlock-cn/mishanguc/files/11499244/minecraft-exported-crash-info-2023-05-17T22-26-04.zip)

**Comment by SolidBlock-cn** [comment]
能否具体说一下是什么报错吗？我查阅了游戏日志，未发现与本模组有关的报错内容。
