### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by XaoooX** [SolidBlock-cn/mishanguc#5]
[crash-2023-08-03_22.16.34-client.txt](https://github.com/SolidBlock-cn/mishanguc/files/12251804/crash-2023-08-03_22.16.34-client.txt)
[2023-08-03-5.log.gz](https://github.com/SolidBlock-cn/mishanguc/files/12251816/2023-08-03-5.log.gz)

**Comment by SolidBlock-cn** [comment]
您的反馈已收到。疑似是由access widener未生效导致的，但具体原因不清楚。或许与Fabric Loader版本有关。
我会继续调查此问题。

**Comment by SolidBlock-cn** [comment]
我这边进行了本地测试，使用Fabric Loader 0.14.22，Fabric API 0.76.0，迷上城建1.2.4，游戏是正常启动的。

**Comment by XaoooX** [comment]
好的，谢谢您，我再尝试一下

**Comment by XaoooX** [comment]
[错误报告-2023-8-4_21.49.42.zip](https://github.com/SolidBlock-cn/mishanguc/files/12261337/-2023-8-4_21.49.42.zip)
you报错了，会不会石和其他模组冲突了

**Comment by SolidBlock-cn** [comment]
不清楚是不是由于模组冲突。您可以尝试：
- 删除并重新安装Fabric API。
- 检查有没有除Fabric API之外的模组*内嵌*了Fabric Data Generation API（从你的崩溃报告来看似乎没有）。
- 临时禁用掉其他模组（本模组依赖的除外），尝试能否启动。
