### ISSUE TITLE
模组告示牌服务器使用时除输入人以外其他人无法看见输入内容

### ISSUE THREAD

**Issue by xiaobaimao233** [SolidBlock-cn/mishanguc#7]
如下
↓本人输入文字后视角
![3eb90bc957fce8c0da3be28468ab2ca0](https://github.com/SolidBlock-cn/mishanguc/assets/64121953/def0c979-8036-413a-ab1a-0dfbf2fa2c08)
↓其他人视角（看不到任何内容）
![6a17572f6e9ab7048d2c15c5bf8665f5](https://github.com/SolidBlock-cn/mishanguc/assets/64121953/2ba7f7c9-fe98-4da2-b28c-4e3ba237c90b)
希望能查明是什么原因并修复它或给出解决办法，谢谢！

**Comment by SolidBlock-cn** [comment]
我会对此进行核实。感谢反馈。

**Comment by xiaobaimao233** [comment]
> 我会对此进行核实。感谢反馈。

还有一个问题就是这个输入确实是不行，但是用复制文字的棍子复制出来别人是能看到的（以及复制的棍子也有个问题，y轴复制后数值不对）

**Comment by SolidBlock-cn** [comment]
此问题应该已经修复于最新版本。请留意模组更新。
