### ISSUE TITLE
Question - how to break the invisible wall sign?

### ISSUE THREAD

**Issue by tanyan-tanyan** [SolidBlock-cn/mishanguc#9]
Hi, I don't think what I'm experiencing is a bug, however I have been struggling with figuring out how to break an invisible wall sign.
It's set to unbreakable so I assume I need one of the tools, but I couldn't figure it out after going through the list of tools this mod gives.

**Comment by SolidBlock-cn** [comment]
It seems my fault, as I made it craftable in Survival Mode. I'll change it in the next version.
